config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :pet_histories
  resources :pets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/pet.rb
class Pet < ApplicationRecord
    has_many :petHistories
end

app/models/pet_history.rb
class PetHistory < ApplicationRecord
  belongs_to :pet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:nombre, :correo, :telefono)
    end
end

app/controllers/pet_histories_controller.rb
class PetHistoriesController < ApplicationController
  before_action :set_pet_history, only: [:show, :edit, :update, :destroy]

  # GET /pet_histories
  # GET /pet_histories.json
  def index
    @pet_histories = PetHistory.all
  end

  # GET /pet_histories/1
  # GET /pet_histories/1.json
  def show
  end

  # GET /pet_histories/new
  def new
    @pet_history = PetHistory.new
  end

  # GET /pet_histories/1/edit
  def edit
  end

  # POST /pet_histories
  # POST /pet_histories.json
  def create
    @pet_history = PetHistory.new(pet_history_params)

    respond_to do |format|
      if @pet_history.save
        format.html { redirect_to @pet_history, notice: 'Pet history was successfully created.' }
        format.json { render :show, status: :created, location: @pet_history }
      else
        format.html { render :new }
        format.json { render json: @pet_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pet_histories/1
  # PATCH/PUT /pet_histories/1.json
  def update
    respond_to do |format|
      if @pet_history.update(pet_history_params)
        format.html { redirect_to @pet_history, notice: 'Pet history was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet_history }
      else
        format.html { render :edit }
        format.json { render json: @pet_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pet_histories/1
  # DELETE /pet_histories/1.json
  def destroy
    @pet_history.destroy
    respond_to do |format|
      format.html { redirect_to pet_histories_url, notice: 'Pet history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet_history
      @pet_history = PetHistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_history_params
      params.require(:pet_history).permit(:peso, :altura, :descripcion, :pet_id)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
    
    @pet_history = PetHistory.pluck(:id)

  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:nombre, :raza, :nacimiento)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pet_histories_helper.rb
module PetHistoriesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :correo %>
    <%= form.text_field :correo %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.number_field :telefono %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>ID Cliente</th>
      <th>Nombre</th>
      <th>Correo</th>
      <th>Telefono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.id %></td>
        <td><%= client.nombre %></td>
        <td><%= client.correo %></td>
        <td><%= client.telefono %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @client.nombre %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @client.correo %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @client.telefono %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppVet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  

  <body>

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">




    <ul class="navbar-nav">
    <button type="button" class="btn btn-light mr-2"><%= link_to 'Inicio', root_path %></button> 
    <button type="button" class="btn btn-light mr-2"><%= link_to 'Nueva Mascota', new_pet_path %></button> 
<button type="button" class="btn btn-light mr-2"><%= link_to 'Nuevo Registro', new_pet_history_path %></button>
    <button type="button" class="btn btn-light mr-2"><%= link_to 'Nuevo Cliente', new_client_path %></button>
    </ul>

</nav>
    <%= yield %>
    </div>
  </body>
</html>

app/views/pet_histories/_form.html.erb
<%= form_with(model: pet_history, local: true) do |form| %>
  <% if pet_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet_history.errors.count, "error") %> prohibited this pet_history from being saved:</h2>

      <ul>
      <% pet_history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :peso %>
    <%= form.number_field :peso %>
  </div>

  <div class="field">
    <%= form.label :altura %>
    <%= form.number_field :altura %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="field">
    <%= form.label :"ID Mascota" %>
    <%= form.text_field :pet_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pet_histories/edit.html.erb
<h1>Editing Pet History</h1>

<%= render 'form', pet_history: @pet_history %>

<%= link_to 'Show', @pet_history %> |
<%= link_to 'Back', pet_histories_path %>

app/views/pet_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pet Histories</h1>

<table>
  <thead>
    <tr>
      <th>ID Mascota</th>
      <th>Peso</th>
      <th>Altura</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pet_histories.each do |pet_history| %>
      <tr>
        <td><%= pet_history.pet_id %></td>
        <td><%= pet_history.peso %></td>
        <td><%= pet_history.altura %></td>
        <td><%= pet_history.descripcion %></td>
        <td><%= link_to 'Show', pet_history %></td>
        <td><%= link_to 'Edit', edit_pet_history_path(pet_history) %></td>
        <td><%= link_to 'Destroy', pet_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet History', new_pet_history_path %>

app/views/pet_histories/new.html.erb
<h1>New Pet History</h1>

<%= render 'form', pet_history: @pet_history %>

app/views/pet_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Peso:</strong>
  <%= @pet_history.peso %>
</p>

<p>
  <strong>Altura:</strong>
  <%= @pet_history.altura %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @pet_history.descripcion %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @pet_history.pet %>
</p>

<%= link_to 'Edit', edit_pet_history_path(@pet_history) %> |
<%= link_to 'Back', pet_histories_path %>

app/views/pets/_form.html.erb
<%= form_with(model: pet, local: true) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :raza %>
    <%= form.text_field :raza %>
  </div>

  <div class="field">
    <%= form.label :nacimiento %>
    <%= form.text_field :nacimiento %>
  </div>

    <div class="field">
    <%= form.label :"ID Cliente" %>
    <%= form.text_field :client_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table>
  <thead>
    <tr>
      <th>N° Visitas</th>
      <th>Nombre</th>
      <th>Raza</th>
      <th>Nacimiento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.petHistories.count %></td>
        <td><%= pet.nombre %></td>
        <td><%= pet.raza %></td>
        <td><%= pet.nacimiento %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Ficha mascota: <%= @pet.nombre%></h1>

<table>
  <thead>
    <tr>
      <th>ID Visita</th>
      <th>Fecha de visita</th>
      <th>Peso</th>
      <th>Altura</th>
      <th>Notas</th>
    </tr>
  </thead>


  <tbody>
    <% @pet.petHistories.each do |h| %>
      <tr>
        <td><%= h.id %></td> 
        <td><%= h.created_at %></td>
        <td><%= h.peso %> Kg</td>
        <td><%= h.altura %> cms</td>
        <td><%= h.descripcion %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>

<br><br>

<table>
  <thead>
    <tr>
      <th>Peso Máximo</th>
      <th>Altura Máxima</th>
      <th>Peso Promedio</th>
      <th>Altura Promedio</th>

    </tr>

  </thead>

  <tbody>

    <tr>
      <td><%= @pet.petHistories.maximum(:peso) %></td>
      <td><%= @pet.petHistories.maximum(:altura) %></td>
      <td><%= @pet.petHistories.average(:peso) %></td>
      <td><%= @pet.petHistories.average(:altura) %></td>

    </tr>

  </tbody>

</table>

<br><br>

<%= link_to 'Back', pets_path %>